try:
    result = 45/0
except:
    print('error')
finally:
    print('error handled')
